### ISSUE TITLE
Track Down ComplexWarning

### ISSUE THREAD

**Issue by kkappler** [simpeg/aurora#138]
When I run
```
python test_compare_synthetic_processing_with_archived_results.py
```

in aurora/tests/synthetic/ I get hosed with ComplexWarning statements.  Not sure exactly where these are coming from.

@timronan if you saw the place this is from while you were cleaning up the code can you flag it and add a note to this issue -- I'd like to know the source of these warnings.
![ComplexWarning](https://user-images.githubusercontent.com/1154939/142963363-b46504d2-7b92-47c3-87cf-9e0005dd3ea7.png)

**Comment by timronan** [comment]
@kkappler I saw this warning also. This warning doesn't seem to be coming from print statements like the other messages. I would guess this is a associated with the exception handling system and how messages are getting passed between xarray and Aurora. I'll look for it tomorrow. I am going to update the docs a bit also.

**Comment by kkappler** [comment]
@timronan This error is coming from 
transfer_function/base.py around line 306 (on my current branch) where the standard error is being set.  It is because a sqrt is being applied to a complex number.
I need to do a bit of homework to determine if I should be taking real(), or abs() of the quantities before/after the product within the sqrt.

```
standard_error.loc[out_ch, inp_ch, T] = np.sqrt(cov_ss * cov_nn)
```

**Comment by kkappler** [comment]
fixed on branch fix_108_mestimator.  Merged into main.
