### ISSUE TITLE
Add a test dataset to validate against EMTF

### ISSUE THREAD

**Issue by kkappler** [simpeg/aurora#17]
Relates to #14 

It maybe nice to make an integrated test out of this.  When a commit is done this test can be run and if the aurora TFs are not np.close() to the EMTF ones the commit is flagged

Earthscope Test

**Comment by kkappler** [comment]
Devlopement of plan for working the  earthscope data is [here](https://docs.google.com/presentation/d/1tctRK8aMVvbuZp7uFbm3n6DEXLlXPDhKHrkzyXQ338E/edit#slide=id.ge1371463aa_0_5)

House the data at IRIS at have an integrated test that generates and processes an mth5

**Comment by kkappler** [comment]
@kujaku11 to wrap these data as an mth5

**Comment by kkappler** [comment]
mth5 success.  Next step is test run through aurora driver

**Comment by kkappler** [comment]
@kujaku11 I tried loading the mth5 that we created on Friday but I get an error when I try to read it:

m = MTH5()
m.open_mth5(SYNTHETIC_DATA, mode="r")
mth5.utils.exceptions.MTH5Error: Input file is not a valid MTH5 file

**Comment by kujaku11** [comment]
@kkappler  Try opening the file with an mode="a", for append that way you can read and write an existing file.

If you  open with "w" it will overwrite the existing file.  Looks like trying to open with "r" returns an error which is a bug, I'll add an issue to MTH5.

**Comment by kujaku11** [comment]
@kkappler added  [MTH5 issue #36](https://github.com/kujaku11/mth5/issues/36) and fixed it.  The updated code is now in master, which has been merged with experiment to get ready to release a beta version on wednesday.  

If you open a file in mode="r" a warning is raised to alert the user that the file is not writeable.

**Comment by kkappler** [comment]
OK, I've got the run_ts time series up and ready to go, I can window, taper, and Fourier transform.  

Next step is calibration.  We will need to check with Gary what filters we need to add, for now I thought I would just add a dummy coefficient filter that multiplies by 1.

@kujaku11 
I tried 
from mt_metadata.timeseries.filters.coefficient_filter import CoefficientFilter
coeff_filter = CoefficientFilter()
m.survey_group.metadata.filters["filter1"] = coeff_filter
but the dictionary doesn't pick up an entry.

Is there an example way to:
1. without an xml, populate the survey filters with some values?
2. To associate each channel with that filter as well?
You can feel free to add examples to:
aurora/data/emtf_synthetic/make_mth5_from_asc.py
inside the method
create_mth5_synthetic_file()

**Comment by kujaku11** [comment]
@kkappler you should be able to do something like:


```
from mt_metadata.timeseries.filters import CoefficientFilter
cf = CoefficientFilter()
cf.units_in = "digital counts"
cf.units_out = "millivolts"
cf.gain = 1.0
cf.name = "unit_conversion"
cf
Out[38]: 
{
    "coefficient_filter": {
        "calibration_date": "1980-01-01",
        "gain": 1.0,
        "name": "unit_conversion",
        "type": "coefficient",
        "units_in": "digital counts",
        "units_out": "millivolts"
    }
}

cf_group = m.filters_group.add_filter(cf)
```

**Comment by kkappler** [comment]
Rudimentary tools for comparison (plot and z-file interface ) exist.
This issue is basically closed but we still need to get agreement as exact as possible.
The steps involved to do that include:
-refine z-file writer with declination and FORTRAN style numerics, and correct carraige returns
-step by step through the fortran processing parameters so that the metadata in aurora zss file agrees with that in the FORTRAN
-get a read on the matlab .zss file:
iris-mt-scratch/iris_mt_scratch/egbert_codes-20210121T193218Z-001/egbert_codes/matlabPrototype_10-13-20/test/syntheticTests/TS1_zss.mat

![test1_comparison_20210725_hamming](https://user-images.githubusercontent.com/1154939/126923419-f3eb57e0-9202-4f2f-a418-6e55f24def9a.png)
![test1_comparison_20210725_dpss](https://user-images.githubusercontent.com/1154939/126923424-8b39e40f-dcdb-48f4-a7e3-9bcc2e0d3205.png)
![z_file_compare_aurora_vs_fortran](https://user-images.githubusercontent.com/1154939/126923665-a898b966-37f8-4f23-87e9-df2213eb8348.png)

**Comment by kkappler** [comment]
The synthetic test dataset is added and integrated has tests
