### ISSUE TITLE
LinAlgError encountered in processing MT data 

### ISSUE THREAD

**Issue by jiajiasun** [simpeg/aurora#233]
Hello,

I got this error message 'LinAlgError: Singular Matrix' when processing MT data from stations "NMY23" "NMY24" in Survey "CONUS South". Below are some codes and two screenshots  that might help understand the error.

mth5_run_summary = RunSummary()
mth5_run_summary.from_mth5s([mth5_path,])
run_summary = mth5_run_summary.clone()
run_summary.mini_summary

kernel_dataset = KernelDataset()
kernel_dataset.from_run_summary(run_summary,"NMY23","NMY24")
kernel_dataset.drop_runs_shorter_than(10000)
kernel_dataset.mini_summary
![Capture](https://user-images.githubusercontent.com/379368/196825737-7bc5fa79-c4f8-4e42-b478-efd8271ba9f8.PNG)

![Capture2](https://user-images.githubusercontent.com/379368/196825930-64c3b769-7301-451a-ad63-4b7bf40d1048.PNG)

**Comment by kkappler** [comment]
The last runs in both "NMY23" and "NMY24" are identically zero-valued in the time series
![image](https://github.com/simpeg/aurora/assets/1154939/d060a25a-f711-49f8-beef-3237f6a98b54)
![image](https://github.com/simpeg/aurora/assets/1154939/f22a0792-68c1-482e-8f76-a81ee1c67d9e)

These make up the majority of the data going into the processing.  The edf method seems to wind up down-weightng all the real data after about 8 iterations.

There are several fixes for this, with the most preferable being to not admit runs that have all zero value into the processing in the first place.  I will see what can be done about tagging all-zero runs as invalid in the processing_summary dataframe.

**Comment by kkappler** [comment]
Zero-runs are treated as invalid.  This functionality is now in mtpy.
