### ISSUE TITLE
test_doc_build.py suddenly failing on python 3.9+ but not on 3.8

### ISSUE THREAD

**Issue by kkappler** [simpeg/aurora#283]
This is happening on the current dev branch `fourier_coefficients`
First observed on Wednesday Aug 29, 2023.

Python 3.9 tests fail with the following summary, but 3.8 is passing.

=========================== short test summary info ============================
FAILED tests/test_doc_build.py::Doc_Test::test_html - AssertionError: False is not true
=========== 1 failed, 49 passed, 26206 warnings in 672.77s (0:11:12) ===========

@laura-iris can you take a look at this?

**Comment by jcapriot** [comment]
Took a preliminary look through the error messages myself... My guess is it is related to a failing notebook example:
https://github.com/simpeg/aurora/actions/runs/6116597192/job/16602042600#step:6:89

There error says 
```
Notebook error:
NoSuchKernel in examples/placeholder.ipynb:
No such kernel named python3
```

**Comment by jcapriot** [comment]
It is likely created during the sphinx-gallery translation of https://github.com/simpeg/aurora/blob/fourier_coefficients/tutorials/placeholder.py

**Comment by kkappler** [comment]
Thanks @jcapriot, and @laura-iris, deletion of the stale placeholder file does allow the test to pass.

This is probably OK for now, but it would be good to actually have a `placeholder.py` that does work, so that we could follow that template if we want to add a py file in tutorials folder.

@laura-iris We can discuss/prioritize this afternoon. It might be better to reduce the ~200 lines of warnings in test_doc_build results before digging into placeholder.py.

I know that there are ipynbs in the repo that reference kernels that are not present during testing (where I beleive the environment is called `aurora-test` and it maybe better to focus for example on issue #45 first and get all the ipynb updated to work in that environment before tackling the rest of this issue.

FWIW I paste the placeholder.py contents below:

```
"""
Placeholder for example
===========================

This example is a placeholder that uses the sphinx-gallery syntax
for creating examples
"""

import aurora
import numpy as np
import matplotlib.pyplot as plt

###############################################################################
# Step 1
# ------
# Some description of what we are doing in step one

x = np.linspace(0, 4 * np.pi, 100)

# take the sin(x)
y = np.sin(x)


###############################################################################
# Step 2
# ------
# Plot it

fig, ax = plt.subplots(1, 1)
ax.plot(x, y)
```

**Comment by laura-iris** [comment]
By adding a file called requirements.txt under docs/ I was able to get the tests to pass on all python versions:

```
cat docs/requirements.txt
ipykernel
```

https://github.com/simpeg/aurora/actions/runs/6124926152/job/16625895596

**Comment by laura-iris** [comment]
Or maybe my work just overlapped with yours Karl

**Comment by kkappler** [comment]
Yes, I had deleted the placeholder.py file. I just added it back in, and the tests do not pass.
I'll leave this branch alone so you an experiment with the requirements:)

**Comment by laura-iris** [comment]
Shoot, it looks like it was just overlapping with your work: https://github.com/simpeg/aurora/actions/runs/6125052883/job/16626254946

**Comment by laura-iris** [comment]
I worked on clearing out a bunch of the auto-documentation warnings, so that could be quieter in the logs - I think that there is still work to be done to make sure that the documentation is complete, but the format has been shifted so that sphinx no longer complains.

After I did that, I removed the bandaid and changed nbsphinx_allow_errors  back to False in conf.py, and when the test ran they all still passed.  Looking at it, sphinx had an update around 10 days ago, and the 3.9+ tests use the latest (7.2.6) - I suspect this has fixed the error associated with template.py.

**Comment by kkappler** [comment]
Thanks @laura-iris, did you push?  

Depending on where the changes I'd like to merge them into fourier_coefficients branch, but I already did a merge with main in anticipation of tagging later this week.  If you push your updates I'll take a look at merging them.

**Comment by laura-iris** [comment]
Yeah, all of the changes were pushed to https://github.com/simpeg/aurora/tree/fix_issue_283 as I was iteratively fixing warnings, running tests, fixing warnings, etc.

**Comment by kkappler** [comment]
Thanks @laura-iris ! The bug is gone and for what it’s worth the output in the gthub actions for test_doc_build is now ~50% the size.   I count 132 readable lines, down from 247 garbled ones – see attached .txt files for the record.

[test_doc_build_pre_issue_283.txt](https://github.com/simpeg/aurora/files/13311947/test_doc_build_pre_issue_283.txt)
[test_doc_build_post_issue_283.txt](https://github.com/simpeg/aurora/files/13311948/test_doc_build_post_issue_283.txt)
