### ISSUE TITLE
Be able to Cite Aurora: Get a DOI

### ISSUE THREAD

**Issue by kujaku11** [simpeg/aurora#315]
@kkappler I want to cite Aurora but there's not a great way.  A simple way to get your code citeable is to get a DOI.  The easiest way is to go to https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content.  Its nice too cause you don't have to update it, it will update with a release tag.

**Comment by kkappler** [comment]
@kujaku11 Thanks for the link.  I have added aurora to zenodo.  Looks like next release will trigger a DOI.  Next release should (hopefully) be in January (fix_issue_36, add support for units)
![image](https://github.com/simpeg/aurora/assets/1154939/3395e1f6-9ba0-41ee-8355-221967af6e56)

**Comment by kujaku11** [comment]
@kkappler nice, you might want to make  a new release just for zenodo to get it setup. Up to you. I can help if you need.

**Comment by kkappler** [comment]
@kujaku11 I'm good with creating a release but would like to get the outstanding PRs on [mth5](https://github.com/kujaku11/mth5/pull/184) and [mt_metadata](https://github.com/kujaku11/mt_metadata/pull/185) accepted so that the  .github/workflows/tests.yaml can refer to main branches for the release.

**Comment by kkappler** [comment]
https://zenodo.org/records/10494538

**Comment by kkappler** [comment]
Will close this issue after the JOSS manuscript is accepted and merged into main.

This will also resolve

- [ ] Issue #194

**Comment by kkappler** [comment]
Besides the old zenodo, we now have two new DOIs associated with the JOSS manuscript:
- https://joss.theoj.org/papers/10.21105/joss.06832
- https://zenodo.org/records/13334589
The zenodo reflects the `joss` branch at the time of publication acceptance (v0.3.13).
