### ISSUE TITLE
[JOSS Review] Add a CITATION.cff file

### ISSUE THREAD

**Issue by blsqr** [simpeg/aurora#346]
(Part of the review process of [a submission to JOSS](https://github.com/openjournals/joss-reviews/issues/6832))

I would suggest to add a [`CITATION.cff` file](https://citation-file-format.github.io) to this repository, populated with citation information of the (upcoming) JOSS publication. Also note the [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) regarding this topic.

Of course this can only be done once the paper has been fully published and a DOI is available.

**Comment by kkappler** [comment]
Thanks @blsqr for you helpful review and suggestions -- we appreciate it!
There is now a CITATION.cff in the [new release](https://pypi.org/project/aurora/) aurora 0.4.1

**Comment by blsqr** [comment]
Happy to hear! Best wishes for the further development of aurora :)
