### ISSUE TITLE
Add Support for Units

### ISSUE THREAD

**Issue by kkappler** [simpeg/aurora#36]
We should support both SI (V/m, T) and MT (mV/km, nT) units.

Right now the Parkfield data calibrate into T and we are working around this in a non-robust way.

If we are only going to support MT units at this point, then we still need to at a minimum add a T-->nT filter to the parkfield.h5 file.

Here is a [tutorial](https://realpython.com/primer-on-python-decorators/) on using pint and decorator methods for units support.

**Comment by kkappler** [comment]
Besides supporting units, this issue relates to defining the units of and standardizing the mt_metadata, which in turn relates to teh station_xml. See issue #31

**Comment by kujaku11** [comment]
@kkappler for the units I've slowly been building a dictionary with the structure: 

```
{
  "digital counts": 
      {
          "abbreviation": "cnts",
           "description": "digital counts",
           "obspy": "counts",
           "plot_label": "Digital Counts"
        },
  "volts": 
        {
            "abbreviation": "V",
            "description": "volts - measurement of electric potential",
            "obspy": "volts",
            "plot_label": "Volts"
         },
}

```
This is going to be a very large dictionary, but should work.  Do you have any other suggestions?

**Comment by kkappler** [comment]
Not yet ... at this point I think the best thing to do is expose the units we practically use and once that list stabilizes we can pick an agreed upon pathway forward.  The question I have is: is there around a half dozen specialized units we need to support within the package (desireable) or do we need to interface with no intermediate package to a fully generalized library of representations ... I guess what I mean is that if we have only a few use cases, lets label them and plug them into a translator that handles all cases rather than build it out internally ...

**Comment by kkappler** [comment]
Thinking more about this, it maybe that support for units doesn't really belong in the _processing_ code.  It would seem better to place the conversion stuff in mth5.  

To be discussed...

**Comment by kkappler** [comment]
A few notes before creating a ticket in MTH5 for this:
- [ ] There seems to be an inconsistency in the filter nomenclature.  For a filter in a channel_ts to be "applied" is False by default, and True when the instrument response if corrected.  This is OK, but the final units of the time series, seem correct but they correspond to filter "units_in" of the last stage, _not_ filter_units_out.  

It would seem correct that if a filter were "applied" then the units of the time series to which it was applied would be "filter units_out" ... 

Players on the stage are: 
"applied", "units_in", "units_out", and the units associated with the Channel_TS object

Question: Do we get to choose "units_in" or "units_out"? Or is this given by the StationXML ?... need to check this

**Comment by kkappler** [comment]
This is done.  Awaiting PR merges on mt_metadata and mth5 before finishing this PR.
