### ISSUE TITLE
Quick Start Guide

### ISSUE THREAD

**Issue by kkappler** [simpeg/aurora#70]
Once we have a documentation page we should have a QSG that tells the user how to pip install, and how to run the tests.  It would then point the user to Jupyter notebooks for making examples.

**Comment by kkappler** [comment]
Joe has some ideas about where to go with documentation. Let's have a discussion about this

**Comment by timronan** [comment]
@kkappler @lheagy here is the outline for the https://github.com/simpeg/aurora/blob/enhancement_71/examples/MTH5_Aurora_End2End.ipynb quick start guide. As said in the meeting, this should probably be done before phase two so we can at least have 1 beta tester on this software stack. If no one except @kkappler can run aurora how is it supposed to be a viable code base? This guide will give users a toe hold into the program. 

The RFP states:

>  This software will serve a growing community of new users, we would like this software to provide a simple, well-documented, user friendly interface for MT data processing that is open source and designed in a way that encourages community contributions and targeted developments in the future.

Outlining the steps required to run this code in documentation is critical  for "encourages community contributions".

**Comment by kkappler** [comment]
Add links in the documentation to the notebooks the do the basic processing (given the existing tutorials and Short Course materials) before closing this out.

**Comment by kkappler** [comment]
Installation instructions and links to example Jupyter notebooks are [here](https://simpeg.xyz/aurora/), as well as on github.
