### ISSUE TITLE
Store Transfer Function as an Xarray

### ISSUE THREAD

**Issue by kujaku11** [simpeg/aurora#93]
It would be convenient if the transfer function and covariances were stored in an xarray.DataSet.  The coordinate could be period or frequency, and dims or variables could be zxx, zxy, zyy, zyx, tzx, tzy, ...  

I am suggesting this because this is what I'm trying to do with MTpy and mt_metadata.  I'd like core container for any type of transfer function that can have metadata attached.  Then we can translate to/from that core container.  Added a similar issue [mt_metadata issue 57](https://github.com/kujaku11/mt_metadata/issues/57)

**Comment by kkappler** [comment]
We could have a attribute _Zij(self) that returns an xarray keyed with "Zxx", "Zxy","Zyx","Zyy",   
then property Zij(self) returns this xarray, creating it if it doesn't already exist.

**Comment by kkappler** [comment]
We want to have a view of a TransferFunctionCollection that is merged on decimation levels.

For now, this will be 3D, but can be 4D later with decimation level.  

We will throw warnings about duplicate periods and default to keep the estimate the had more observations

**Comment by kkappler** [comment]
@kujaku11 
I added a method to TransferFunctionCollection called merge_decimation_levels()
This returns a dict "merged_dict" with the following entries:
dict_keys(['tf', 'tf_xarray', 'cov_ss_inv', 'cov_nn'])

If you access:
merged_dict["tf_xarray"] that has all the transfer function elements keyed as you suggest.

Can you take a look and see if that works for you?  I can reformat the covariances as well if we decide on nomenclature, but as it stands they can be accessed by keys of input_channel_1, input_channel_2 (for inverse signal covariance) and output_channel_1 and output_channel_2 for noise covariance

**Comment by kujaku11** [comment]
@kkappler Nice, I think this is what I was looking for.  Probably down the road the full transfer function with covariances could be a DataSet that share the coordinate period.  

Should this transfer function object live in mt_metadata?  I was thinking that could be the central location where everything get put into a common container and would avoid circular imports.  For example in aurora it would be 
`from mt_metadata.transfer_function import core`

Instead of in mt_metadata:
`from aurora import TransferFunction`

**Comment by kkappler** [comment]
@kujaku11 Agreed -- The core data structure for TF should live in mt_metadata.   I think we do not want mt_metadata (or mth5) to have to import from aurora.

Note that the covariances already exist as xarray Datasets with coordinate "period" in the merged_dict.  I was tempeted to create a class called 
```
MergedTransferFunction
```
 or something like that to use instead of the dictionary.    But it seems like what I actually want is

``` 
from mt_metadata.transfer_function.base import TransferFunction as MergedTransferFunction
```

Then an instance of mt_metadata's transfer function would get populated and returned by  
TransferFunctionCollection.merge_decimation_levels()

**Comment by kujaku11** [comment]
@kkappler That sounds good.  I will try to build that code by Friday starting from what you have.

**Comment by kkappler** [comment]
I confirm that aurora tests are passing using the main branch of mt_metadata after the fix_2 merge.
